CREATE TABLE Employes (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255),
    Position VARCHAR(100),
    Status INT DEFAULT 1,
    create_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_date DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Customers (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255),
    Status INT DEFAULT 1,
    create_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_date DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Companies (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255),
    Status INT DEFAULT 1,
    Description TEXT,
    EmployeeID INT NOT NULL,
    create_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (EmployeeID) REFERENCES Employes(ID)
);



CREATE TABLE Products(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255),
    Description TEXT,
    Price DECIMAL(10, 2),
    Status INT DEFAULT 1,
    CompanyID INT NOT NULL,
    EmployeeID INT NOT NULL,
    create_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (EmployeeID) REFERENCES Employes(ID),
    FOREIGN KEY (CompanyID) REFERENCES Companies(ID)
);

CREATE TABLE Units(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255),
    Description TEXT,
    Price DECIMAL(10, 2),
    Status INT DEFAULT 1

);

CREATE TABLE Purchases(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ProductID INT NOT NULL,
    CustomerID INT NOT NULL,
    Price DECIMAL DEFAULT 0, -- 14500
    UnitID INT NOT NULL,
    Total DECIMAL DEFAULT  0,
    EmployeeID INT NOT NULL,
    create_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ProductID) REFERENCES Products(ID),
    FOREIGN KEY (CustomerID) REFERENCES Customers(ID),
    FOREIGN KEY (UnitID) REFERENCES Units(ID)

);



-- CRM
CREATE TABLE CustomersAddresses(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CustomerID INT NOT NULL,
    Address VARCHAR(255),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CustomerID) REFERENCES Customers(ID)
);

CREATE TABLE CompaniesAddresses(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CompanyID INT NOT NULL,
    Address VARCHAR(255),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CompanyID) REFERENCES Companies(ID)
);



-- CREATE TABLE Order (
--     ID INT AUTO_INCREMENT PRIMARY KEY,
--     CustomerID INT,
--     OrderDate DATE,
--     TotalAmount DECIMAL(10, 2),
--     FOREIGN KEY (CustomerID) REFERENCES Customer(CustomerID)
-- );

-- CREATE TABLE OrderDetail (
--     ID INT AUTO_INCREMENT PRIMARY KEY,
--     OrderID INT,
--     ProductID INT,
--     Quantity INT,
--     UnitPrice DECIMAL(10, 2)
--     FOREIGN KEY (OrderID) REFERENCES Order(OrderID),
--     FOREIGN KEY (ProductID) REFERENCES Product(ProductID)
-- );

